#!/usr/bin/env python3
"""Generate a portable requirements.lock.txt without editable absolute paths."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LOCK = ROOT / "requirements.lock.txt"


def main() -> int:
    raw = subprocess.check_output(
        [sys.executable, "-m", "pip", "freeze", "--exclude-editable"],
        cwd=ROOT,
        text=True,
    )
    lines = []
    for line in raw.splitlines():
        if not line or line.startswith("#"):
            continue
        if line.startswith("-e ") or "file://" in line or "/Users/" in line:
            continue
        if line.lower().startswith("cloud-data-sanitizer"):
            continue
        lines.append(line)
    lines = sorted(set(lines), key=str.lower)
    header = [
        "# Portable dependency lock for Cloud Data Sanitizer.",
        "# Generated by scripts/generate_lockfile.py",
        "# Install: pip install -r requirements.lock.txt && pip install '.[dev,desktop]'",
        "",
    ]
    LOCK.write_text("\n".join(header + lines) + "\n", encoding="utf-8")
    for line in lines:
        if "/Users/" in line or "file://" in line or line.startswith("-e "):
            raise SystemExit(
                f"FAIL CLOSED: lockfile still contains absolute/editable paths: {line}"
            )
    print(f"Wrote {LOCK} ({len(lines)} packages)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
